auth-generate:
	npx @better-auth/cli generate --config src/lib/auth/auth.ts --output src/database/schema

drizzle-generate:
	npx drizzle-kit generate

drizzle-migrate:
	npx drizzle-kit migrate

install:
	yarn --frozen-lockfile

hello:
	echo 'hello'